### PR TITLE
Miscellaneous improvements

### PR DESCRIPTION
**Pull request by FraGag**
I'm submitting all these changes as a single pull request because the commits have some conflicts with each other. I also wanted to finish all of this before submitting the pull request so that they could all be bundled in the same version.

The major changes are:
* The type of `Entry::source` was `Option<Feed>`. I'm pretty sure it was meant to be `Option<Source>`, so I fixed it. This is a breaking change, so this will require a version bump to 0.2 (Cargo will update 0.x.y to 0.x.z, but not to 0.z.0).
* Remove uses of `Result::unwrap()`. An application I built using rust-atom would panic because of an invalid Atom feed. Instead of panicking, the library now bubbles up errors.
* Stop exporting `Author` and `Contributor`. They are not used anywhere in the API and are not useful by themselves; since the `ViaXml` trait is not public, they have no public methods attached to them.
* Various performance improvements (avoid cloning objects).
* Add extensive unit tests for the whole library.

### CODE REVIEW

**Comment by vtduncan** [comment]
Wow, @FraGag, thank you so much for working on these improvements! It looks like you have put a lot of time into this pull request and I'm really grateful for it.

So many good changes here, especially eliminating the panics — sorry you had to deal with those in your project! I'll go through the commits in depth shortly.

**Comment by vtduncan** [comment]
Ok this is merged now. Thanks again for your work, the library is in much better shape because of it! If you're happy with these changes then I'll tag v0.2.0 and republish the crate.

**Comment by FraGag** [comment]
Sure! Don't forget to change 0.2.0-pre to 0.2.0 in Cargo.toml. :smile:

**Comment by vtduncan** [comment]
Perfect! The new crate is now published.

**Pull request merged**
